/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BeritaIndexRouteImport } from './routes/berita.index'
import { Route as JualIndexRouteImport } from './routes/jual.index'
import { Route as JualFormRouteImport } from './routes/jual.form'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaIndexRoute = BeritaIndexRouteImport.update({
  id: '/berita/',
  path: '/berita/',
  getParentRoute: () => rootRouteImport,
} as any)
const JualIndexRoute = JualIndexRouteImport.update({
  id: '/jual/',
  path: '/jual/',
  getParentRoute: () => rootRouteImport,
} as any)
const JualFormRoute = JualFormRouteImport.update({
  id: '/jual/form',
  path: '/jual/form',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jual/form': typeof JualFormRoute
  '/berita/': typeof BeritaIndexRoute
  '/jual/': typeof JualIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jual/form': typeof JualFormRoute
  '/berita': typeof BeritaIndexRoute
  '/jual': typeof JualIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jual/form': typeof JualFormRoute
  '/berita/': typeof BeritaIndexRoute
  '/jual/': typeof JualIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jual/form' | '/berita/' | '/jual/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jual/form' | '/berita' | '/jual'
  id: '__root__' | '/' | '/jual/form' | '/berita/' | '/jual/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JualFormRoute: typeof JualFormRoute
  BeritaIndexRoute: typeof BeritaIndexRoute
  JualIndexRoute: typeof JualIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/': {
      id: '/berita/'
      path: '/berita'
      fullPath: '/berita/'
      preLoaderRoute: typeof BeritaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jual/': {
      id: '/jual/'
      path: '/jual'
      fullPath: '/jual/'
      preLoaderRoute: typeof JualIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jual/form': {
      id: '/jual/form'
      path: '/jual/form'
      fullPath: '/jual/form'
      preLoaderRoute: typeof JualFormRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JualFormRoute: JualFormRoute,
  BeritaIndexRoute: BeritaIndexRoute,
  JualIndexRoute: JualIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
